import Big from 'big.js';

export default {
    buildingNames: ["Abbey", "A-frame", "Aircraft Hangar", "Airport Terminal", "Amphitheater", "Apartment Building", "Aqueduct", "Arch", "Arena", "Armory", "Assembly Hall", "Barn", "Barracks", "Beach House", "Boathouse", "Boarding House", "Bowling Alley", "Bridge", "Brownstone", "Bungalow", "Bunkhouse", "Bunker", "Cabana", "Cabin", "Capitol", "Carport", "Castle", "Catacomb", "Cathedral", "Chalet", "Chapel", "Chateau", "Church", "Cinema", "City Hall", "Clubhouse", "College", "Compound", "Concert Hall", "Condominium", "Conservatory", "Cottage", "Courthouse", "Crypt", "Depot", "Detached House", "Dock", "Dome", "Dormitory", "Double Wide", "Duplex", "Dwelling", "Embassy", "Exposition Hall", "Factory", "Farm", "Farmhouse", "Ferry Slip", "Ferry Terminal", "Firehouse", "Fire Station", "Folly", "Forge", "Fort", "Fortress", "Foundry", "Gallery", "Garage", "Gas Station", "Gazebo", "Geodesic Dome", "Granary", "Greenhouse", "Gym", "Gymnasium", "Hall", "Hangar", "Haunted House", "Headquarters", "High-rise", "Home", "Hospital", "Hostel", "Hotel", "Hot House", "House", "Houseboat", "Housing Project", "Hunting Lodge", "Hut", "Igloo", "Jail", "Kiosk", "Laboratory", "Lean-to", "Library", "Lighthouse", "Lodge", "Log Cabin", "Longhouse", "Mall", "Manor", "Manse", "Mansion", "Marina", "Market", "Mausoleum", "Meeting Hall", "Mill", "Minaret", "Mobile Home", "Monastery", "Monument", "Mosque", "Motel", "Museum", "Nuclear Power Plant", "Nursing Home", "Observatory", "Office Building", "Opera House", "Outbuilding", "Outhouse", "Pagoda", "Palace", "Parking Garage", "Parliament", "Pavilion", "Plant", "Playhouse", "Police Station", "Pool House", "Post Office", "Power Plant", "Prefab Building", "Prison", "Pump House", "Pyramid", "Quonset Hut", "Railway Station", "Ranch", "Rectory", "Refinery", "Residence", "Restaurant", "Roller Rink", "Roundhouse", "Rowhouse", "School", "Shack", "Shed", "Shelter", "Shopping Center", "Shopping Mall", "Shrine", "Silo", "Skating Rink", "Skyscraper", "Skyway", "Smokestack", "Spire", "Split-level House", "Stable", "Stadium", "State House", "Station", "Steeple", "Store", "Storehouse", "Strip Mall", "Structure", "Studio", "Supermarket", "Symphony", "Synagogue", "Temple", "Tenement", "Tent", "Terminal", "Theater", "Tipi", "Toll House", "Tomb", "Tower", "Townhouse", "Treehouse", "Triplex", "Tudor House", "University", "Vault", "Vicarage", "Villa", "Warehouse", "Watermill", "Workshop", "Yurt"],

    buildings: [
        { name: 0, baseCost: Big(15), buyCost: Big(15), baseCps: Big(0.1), currentCps: Big(0.1), description: "", unlocked: false, showAt: 0, owned: 0 },
        { name: 1, baseCost: Big(100), buyCost: Big(100), baseCps: Big(1), currentCps: Big(1), description: "", unlocked: false, showAt: Big(0), owned: 0 },
        { name: 2, baseCost: Big(1100), buyCost: Big(1100), baseCps: Big(8), currentCps: Big(8), description: "", unlocked: false, showAt: Big(15), owned: 0 },
        { name: 3, baseCost: Big(12000), buyCost: Big(12000), baseCps: Big(47), currentCps: Big(47), description: "", unlocked: false, showAt: Big(100), owned: 0 },
        { name: 4, baseCost: Big(130000), buyCost: Big(130000), baseCps: Big(260), currentCps: Big(260), description: "", unlocked: false, showAt: Big(1100), owned: 0 },
        { name: 5, baseCost: Big(1.4E6), buyCost: Big(1.4E6), baseCps: Big(1400), currentCps: Big(1400), description: "", unlocked: false, showAt: Big(12000), owned: 0 },
        { name: 6, baseCost: Big(20E6), buyCost: Big(20E6), baseCps: Big(7800), currentCps: Big(7800), description: "", unlocked: false, showAt: Big(130000), owned: 0 },
        { name: 7, baseCost: Big(330E6), buyCost: Big(330E6), baseCps: Big(44000), currentCps: Big(44000), description: "", unlocked: false, showAt: Big(1.4E6), owned: 0 },
        { name: 8, baseCost: Big(5.1E9), buyCost: Big(5.1E9), baseCps: Big(260000), currentCps: Big(260000), description: "", unlocked: false, showAt: Big(20E6), owned: 0 },
        { name: 9, baseCost: Big(75E9), buyCost: Big(75E9), baseCps: Big(1.6E6), currentCps: Big(1.6E6), description: "", unlocked: false, showAt: Big(330E6), owned: 0 },
        { name: 10, baseCost: Big(1E12), buyCost: Big(1E12), baseCps: Big(10E6), currentCps: Big(10E6), description: "", unlocked: false, showAt: Big(5.1E9), owned: 0 },
        { name: 11, baseCost: Big(14E12), buyCost: Big(14E12), baseCps: Big(65E6), currentCps: Big(65E6), description: "", unlocked: false, showAt: Big(75E9), owned: 0 },
        { name: 12, baseCost: Big(170E12), buyCost: Big(170E12), baseCps: Big(430E6), currentCps: Big(430E6), description: "", unlocked: false, showAt: Big(1E12), owned: 0 },
        { name: 13, baseCost: Big(2.1E15), buyCost: Big(2.1E15), baseCps: Big(2.9E12), currentCps: Big(2.9E12), description: "", unlocked: false, showAt: Big(14E12), owned: 0 },
    ],

    buildingUpgrades: [
        { type: 0, name: 'Double {TYPE}', needed: 1, cost: Big(100), multiplier: 2, description: 'Tap faster', unlocked: false, active: false },
        { type: 0, name: 'Quattro {TYPE}', needed: 1, cost: Big(500), multiplier: 2, description: 'Tap faster!', unlocked: false, active: false },
        { type: 0, name: 'Mega {TYPE}', needed: 10, cost: Big(10000), multiplier: 2, description: 'Tap even faster!!', unlocked: false, active: false },
        { type: 0, name: 'Middle Finger', needed: 20, cost: Big(100000), addition: 0.1, description: 'Put that thing away.', unlocked: false, active: false },
        { type: 0, name: 'Double Middle Finger', needed: 40, cost: Big(10E6), addition: 0.5, description: 'Put those away.', unlocked: false, active: false },
        { type: 0, name: 'Extra Middle Fingers', needed: 80, cost: Big(100E6), addition: 5, description: "Now that's just rude.", unlocked: false, active: false },
        { type: 0, name: 'Super Finger', needed: 120, cost: Big(1E9), addition: 50, description: "No decorum at all.", unlocked: false, active: false },
        { type: 0, name: 'Super Duper Finger', needed: 160, cost: Big(10E9), addition: 500, description: "Need Description", unlocked: false, active: false },
        { type: 0, name: 'Mega Finger', needed: 200, cost: Big(10E12), addition: 5000, description: "Need Description", unlocked: false, active: false },
        { type: 0, name: 'Turbo Finger', needed: 240, cost: Big(100E12), addition: 50000, description: "Need Description", unlocked: false, active: false },
        { type: 0, name: 'Ultra Finger', needed: 280, cost: Big(1E12), addition: 500000, description: "Need Description", unlocked: false, active: false },
        { type: 0, name: 'Ultimate Finger', needed: 320, cost: Big(10E15), addition: 5000000, description: "Need Description", unlocked: false, active: false },

        { type: 1, name: 'Timeout', needed: 1, cost: Big(1000), multiplier: 2, description: 'These toddlers need to learn some discipline', unlocked: false, active: false },
        { type: 1, name: 'Daycare', needed: 5, cost: Big(5000), multiplier: 2, description: 'Finally, some me time!', unlocked: false, active: false },
        { type: 1, name: 'Play Date', needed: 25, cost: Big(50000), multiplier: 2, description: 'An active social life is good for productivity', unlocked: false, active: false },
        { type: 1, name: 'ADHD Meds', needed: 50, cost: Big(5E6), multiplier: 2, description: "That's better...", unlocked: false, active: false },
        { type: 1, name: 'Jack', needed: 100, cost: Big(500E6), multiplier: 2, description: "Like that movie?", unlocked: false, active: false },
        { type: 1, name: 'Jack & Jill', needed: 150, cost: Big(50E9), multiplier: 2, description: "The worst Adam Sandler movie", unlocked: false, active: false },
        { type: 1, name: 'Need Name', needed: 200, cost: Big(50E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 1, name: 'Need Name', needed: 250, cost: Big(50E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 2, name: 'Torah', needed: 1, cost: Big(11000), multiplier: 2, description: 'Got to follow the rules', unlocked: false, active: false },
        { type: 2, name: 'Another Torah', needed: 5, cost: Big(55000), multiplier: 2, description: 'More to go around', unlocked: false, active: false },
        { type: 2, name: 'Rabbi', needed: 25, cost: Big(550000), multiplier: 2, description: "This rabbi doesn't come cheap", unlocked: false, active: false },
        { type: 2, name: 'Rabbi Council', needed: 50, cost: Big(55E6), multiplier: 2, description: "These rabbis don't come cheap", unlocked: false, active: false },
        { type: 2, name: 'Passover Bonus', needed: 100, cost: Big(5.5E9), multiplier: 2, description: "What does that even mean?", unlocked: false, active: false },
        { type: 2, name: 'Need Name', needed: 150, cost: Big(550E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 2, name: 'Need Name', needed: 200, cost: Big(550E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 2, name: 'Need Name', needed: 250, cost: Big(550E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 3, name: 'Knockoff Torah', needed: 1, cost: Big(120000), multiplier: 2, description: "This doesn't seem legit...", unlocked: false, active: false },
        { type: 3, name: 'Another Knockoff Torah', needed: 5, cost: Big(600000), multiplier: 2, description: "??", unlocked: false, active: false },
        { type: 3, name: 'Fake Rabbi', needed: 25, cost: Big(6E6), multiplier: 2, description: "I don't think his beard is real", unlocked: false, active: false },
        { type: 3, name: 'Fake Rabbi Council', needed: 50, cost: Big(600E6), multiplier: 2, description: "I have a bad feeling about this", unlocked: false, active: false },
        { type: 3, name: 'Fake Passover Bonus', needed: 100, cost: Big(60E9), multiplier: 2, description: "What does that even mean?!", unlocked: false, active: false },
        { type: 3, name: 'Need Name', needed: 150, cost: Big(6E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 3, name: 'Need Name', needed: 200, cost: Big(6E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 3, name: 'Need Name', needed: 250, cost: Big(6E18), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 4, name: 'Strumpets', needed: 1, cost: Big(1.3E6), multiplier: 2, description: "What are we, savages?", unlocked: false, active: false },
        { type: 4, name: 'Valet', needed: 5, cost: Big(6.5E6), multiplier: 2, description: "I'm too rich to park my car", unlocked: false, active: false },
        { type: 4, name: 'Servant', needed: 25, cost: Big(65E6), multiplier: 2, description: "It's not technically slavery!", unlocked: false, active: false },
        { type: 4, name: 'Free trade tea', needed: 50, cost: Big(6.5E9), multiplier: 2, description: "I feel so much better about this", unlocked: false, active: false },
        { type: 4, name: 'Slavery tea', needed: 100, cost: Big(650E9), multiplier: 2, description: "Suffering tastes better", unlocked: false, active: false },
        { type: 4, name: 'Need Name', needed: 150, cost: Big(65E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 4, name: 'Need Name', needed: 200, cost: Big(65E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 4, name: 'Need Name', needed: 250, cost: Big(65E18), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 5, name: 'Strumpets', needed: 1, cost: Big(14E6), multiplier: 2, description: "What are we, savages?", unlocked: false, active: false },
        { type: 5, name: 'Valet', needed: 5, cost: Big(70E6), multiplier: 2, description: "I'm too rich to park my car", unlocked: false, active: false },
        { type: 5, name: 'Servant', needed: 25, cost: Big(700E6), multiplier: 2, description: "It's not technically slavery!", unlocked: false, active: false },
        { type: 5, name: 'Free trade tea', needed: 50, cost: Big(70E9), multiplier: 2, description: "I feel so much better about this", unlocked: false, active: false },
        { type: 5, name: 'Slavery tea', needed: 100, cost: Big(7E12), multiplier: 2, description: "Suffering tastes better", unlocked: false, active: false },
        { type: 5, name: 'Need Name', needed: 150, cost: Big(700E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 5, name: 'Need Name', needed: 200, cost: Big(700E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 5, name: 'Need Name', needed: 250, cost: Big(700E18), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 6, name: 'Need Name', needed: 1, cost: Big(200E6), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 5, cost: Big(1E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 25, cost: Big(10E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 50, cost: Big(1E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 100, cost: Big(100E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 150, cost: Big(10E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 200, cost: Big(10E18), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 6, name: 'Need Name', needed: 250, cost: Big(10E21), multiplier: 2, description: "Need Description", unlocked: false, active: false },

        { type: 7, name: 'Need Name', needed: 1, cost: Big(3.3E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 5, cost: Big(16.5E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 25, cost: Big(165E9), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 50, cost: Big(16.5E12), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 100, cost: Big(1.65E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 150, cost: Big(165E15), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 200, cost: Big(165E18), multiplier: 2, description: "Need Description", unlocked: false, active: false },
        { type: 7, name: 'Need Name', needed: 250, cost: Big(165E21), multiplier: 2, description: "Need Description", unlocked: false, active: false },
    ],

    buildingAchivements: [
        { type: 0, name: 'Click', total: Big(1), unlocked: false },
        { type: 0, name: 'Double Click', total: Big(2), unlocked: false },

        { type: 1, name: 'Grandma basics', total: Big(1), unlocked: false },
        { type: 1, name: 'Grandma proficiency', total: Big(50), unlocked: false }
    ],
}
